import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, liveAnywhereData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        {/* Header */}
        <Header />
        {/* Banner */}
        <Banner />

        <main className="max-w-7xl mx-auto px-8">
          <section>
            <h1 className="text-5xl font-semibold mt-5">Explore Nearby</h1>
            <div className="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {exploreData?.map((item) => (
                <SmallCard
                  key={item.img}
                  img={item.img}
                  location={item.location}
                  distance={item.distance}
                />
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-5xl font-semibold mt-5"> Live Anywhere</h2>
            <div className="flex space-x-3 mt-5 overflow-scroll scrollbar-hide p-3 -ml-3">
              {liveAnywhereData.map((item) => (
                <MediumCard key={item.img} img={item.img} title={item.title} />
              ))}
            </div>
          </section>

          <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlist curated by Airbnb."
            buttomText="Get Inspired"
          />
        </main>

        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  const liveAnywhereData = await fetch(
    "https://www.jsonkeeper.com/b/VHHT"
  ).then((res) => res.json());

  return {
    props: {
      exploreData,
      liveAnywhereData,
    },
  };
}
